// ========================================================================
// Panda Professor — Chengdu Tours Data & i18n
// ========================================================================

const translations = {
  en: {
    indexPageTitle: "Panda Professor - Chengdu Tours",
    indexMetaDescription: "Authentic, private, and deeply knowledgeable tours of Chengdu, guided by local experts.",
    menuLabel: "Menu",
    primaryNavigationAriaLabel: "Primary navigation",
    homeLinkAriaLabel: "Panda Professor home",
    openSidebarAriaLabel: "Open navigation sidebar",
    closeSidebarAriaLabel: "Close navigation sidebar",
    langToggleAriaLabel: "Switch language",
    heroTitleP1: "Discover Chengdu",
    heroTitleP2: "with a Local Scholar",
    heroSubtitle: "Experience the true essence of Sichuan. From intimate panda encounters to hidden culinary treasures, explore my home city through the eyes of a passionate expert.",
    bookNow: "Plan Your Journey",
    viewTours: "Explore Experiences",
    expertGuides: "Expert Guides",
    localScholars: "Local Scholars",
    authenticExp: "Authentic",
    hiddenGems: "Hidden Gems",
    maxComfort: "Max Comfort",
    privatePremium: "Private & Premium",
    ourTours: "Curated Experiences",
    filterAll: "All",
    filterControlsLabel: "Tour filter controls",
    filterCulture: "Culture",
    filterFood: "Food",
    filterNature: "Nature",
    filterPandas: "Pandas",
    filterHistory: "History",
    addToDay: "Add to Day Plan",
    removeFromDay: "Remove from Plan",
    tourFavorite: "Add to favorites",
    tourUnfavorite: "Remove from favorites",
    planItemTime: "Start time",
    planItemDuration: "Duration (hours)",
    planItemPeople: "People",
    planItemHours: "hrs",
    planItemNotesPlaceholder: "Optional notes for this stop (special requests, transport, meal breaks)",
    reviewsTitle: "Traveller Stories",
    sharePlan: "Share Plan",
    clearPlan: "Clear Plan",
    dayBuilderTitle: "Your Custom Day",
    dayBuilderNote: "Drag or click a tour card to add it to your day plan.",
    dayBuilderEmpty: "Your day is empty. Add tours from the list above to build your perfect Panda Professor experience.",
    totalPrice: "Est. Total",
    totalDuration: "Total Time",
    bookPlan: "Request Booking",
    faqTitle: "Frequently Asked Questions",
    bookingTitle: "Booking Request",
    nameLabel: "Full Name",
    emailLabel: "Email Address",
    dateLabel: "Preferred Date",
    guestsLabel: "Number of Guests",
    notesLabel: "Special Requests or Notes",
    bookingNamePlaceholder: "John Doe",
    bookingEmailPlaceholder: "john@example.com",
    bookingNotesPlaceholder: "Any dietary restrictions, flight times, etc.",
    bookingInfoNote: "Note: We use your local email client to securely construct the request. No payment is taken at this stage.",
    bookingSuccessClose: "Got it!",
    submitBooking: "Send Request",
    close: "Close",
    tourInclusions: "What's Included",
    tourExclusions: "Not Included",
    tourItinerary: "Itinerary Highlights",
    language: "Language",
    theme: "Theme",
    searchPlaceholder: "Search tours...",
    copied: "Link copied!",
    linkCopiedMsg: "Your custom day plan link has been copied to your clipboard.",
    bookingSuccessTitle: "Request Ready",
    bookingSuccessMsg: "Your booking request has been generated. Your email client will now open to send the request directly to our team.",
    chatWelcome: "Ni hao! I'm the Panda Professor. 🐼 How can I help you plan your Chengdu adventure today?",
    chatTitle: "Panda Professor",
    chatOnlineStatus: "Online",
    chatInputPlaceholder: "Type your message...",
    chatBtnTours: "Recommend a tour",
    chatBtnFood: "What is Chengdu food like?",
    chatBtnPanda: "Tell me a panda fact!",
    skipToContent: "Skip to content",
    themeSelectLabel: "Theme",
    themeEmerald: "Emerald",
    themeForest: "Forest",
    themeBamboo: "Bamboo",
    searchLabel: "Search tours",
    chatDefaultResponse: "I'm just a demo panda right now 🐾 but I'll make sure a real local expert answers that when you book! Anything else?",
    tourPopular: "Popular",
    tourPriceTime: "Price & Time",
    tourView: "View",
    tourDuration: "Duration",
    tourHours: "Hours",
    tourBasePrice: "Base Price",
    planTbd: "TBD",
    chatResTours: "For first-timers, I highly recommend 'Dawn Panda Conservation Expedition'. For foodies, 'Night Market & Sichuan Food Journey' is unbeatable! 🎋",
    chatResFood: "Chengdu is a UNESCO City of Gastronomy! Expect bold flavors, numbing Sichuan peppercorns, and bubbling hot pots. We can customize the spice level for you. 🌶️",
    chatResPanda: "Did you know a giant panda spends 10-16 hours a day eating? They can eat up to 38kg of bamboo a day! I respect that dedication to snacks. 🎋🐾",
    footerAbout: "Authentic, private, and deeply knowledgeable tours of Chengdu, guided by local experts.",
    footerLinks: "Quick Links",
    footerContact: "Contact",
    footerBrandTagline: "Chengdu Tours",
    footerAriaLabel: "Panda Professor footer",
    footerEmailLabel: "Email",
    footerPhoneLabel: "Phone",
    footerEmailA11y: "Email Panda Professor",
    footerPhoneA11y: "Call Panda Professor",
    footerSocialLabel: "Follow Panda Professor",
    socialLinksLabel: "Social media channels",
    footerQuickLinks: "Quick Links",
    footerPlanning: "Planning",
    footerFollowUs: "Follow",
    footerCta: "Ask us before booking—your private guide is waiting.",
    footerCopyright: "© {year} Panda Professor Chengdu Tours. All rights reserved.",
    footerBrandAriaLabel: "Visit Panda Professor",
    footerQuickLinksAriaLabel: "Footer quick links",
    footerPlanningAriaLabel: "Footer planning links",
    footerSocialNavAriaLabel: "Footer social links",
    footerSocialInstagram: "Instagram",
    footerSocialFacebook: "Facebook",
    footerSocialTwitter: "Twitter",
    footerSocialWeibo: "Weibo",
    footerSocialXiaohongshu: "Xiaohongshu",
    footerSocialWeChat: "WeChat",
    footerSocialWeChatTip: "Scan or search {wechatId} on WeChat",
    closeModalAriaLabel: "Close modal",
    closeBookingFormAriaLabel: "Close booking form",
    closeSuccessMessageAriaLabel: "Close success message",
    chatTriggerAriaLabel: "Open Panda chat assistant",
    chatPanelAriaLabel: "Panda chat assistant",
    chatCloseAriaLabel: "Close Panda chat",
    sendMessageAriaLabel: "Send message",
    adminPageTitle: "Panda Professor — Admin Dashboard",
    adminMetaDescription: "Admin dashboard for Panda Professor Chengdu Tours.",
    adminAdminLogin: "Admin Login",
    adminPinHint: "Enter your admin PIN to access the dashboard.",
    adminInvalidPin: "Invalid PIN. Please try again.",
    adminPinLabel: "Admin PIN",
    adminSignInAriaLabel: "Sign in to admin dashboard",
    adminSignIn: "Sign In",
    adminLanguageToggleAriaLabel: "Switch admin language",
    adminHint: "HINT",
    adminDefaultPin: "Default PIN:",
    adminDefaultPinValue: "admin",
    adminAdminText: "Admin",
    adminViewSite: "View Site",
    adminViewSiteAriaLabel: "Open public site",
    adminLogout: "Logout",
    adminLogoutAriaLabel: "Sign out",
    adminHomeAriaLabel: "Admin dashboard home",
    adminLanguage: "Language",
    adminActiveTours: "Active Tours",
    adminPendingRequests: "Pending Requests",
    adminResolved: "Resolved",
    adminBookingRequests: "Booking Requests",
    adminTourOfferings: "Tour Offerings",
    adminGallery: "Image Gallery",
    adminSettings: "Settings",
    adminReviews: "Reviews",
    adminFaqs: "FAQs",
    adminDate: "Date",
    adminName: "Name",
    adminEmail: "Email",
    adminGuests: "Guests",
    adminTours: "Tours",
    adminStatus: "Status",
    adminActions: "Actions",
    adminNoBookingRequests: "No booking requests yet.",
    adminNoRequestsSub: "Requests submitted on the public site will appear here.",
    adminAddReview: "Add Review",
    adminTravellerStories: "Traveller Stories",
    adminAddFaq: "Add FAQ",
    adminFrequentlyAskedQuestions: "Frequently Asked Questions",
    adminAddNewTour: "Add New Tour",
    adminUploadImage: "Upload Image",
    adminChangeAdminPin: "Change Admin PIN",
    adminNewPin: "New PIN",
    adminNewPinPlaceholder: "Enter new PIN",
    adminUpdatePin: "Update PIN",
    adminPinUpdated: "PIN updated successfully!",
    adminSiteContact: "Site Details & Contact Info",
    adminSiteName: "Site Name",
    adminContactEmail: "Contact Email",
    adminContactPhone: "Contact Phone",
    adminBrandLogo: "Brand Logo URL",
    adminBrandLogoPlaceholder: "logo.png or https://cdn.example.com/logo.svg",
    adminBrandLogoHint: "Used across header, footer, chat, and admin branding.",
    adminSocialLinks: "Social Media Links",
    adminInstagram: "Instagram",
    adminFacebook: "Facebook",
    adminTwitter: "Twitter / X",
    adminWeChat: "WeChat (Username / ID)",
    adminWeibo: "Weibo URL",
    adminXiaohongshu: "Xiaohongshu (RED) URL",
    adminInstagramPlaceholder: "https://instagram.com/...",
    adminFacebookPlaceholder: "https://facebook.com/...",
    adminTwitterPlaceholder: "https://twitter.com/...",
    adminWeChatPlaceholder: "WeChat ID",
    adminWeiboPlaceholder: "https://weibo.com/...",
    adminXiaohongshuPlaceholder: "https://xiaohongshu.com/...",
    adminSettingsSaved: "Settings saved!",
    adminSaveChanges: "Save Changes",
    adminChatCopyHeading: "Chatbot Copy Settings",
    adminChatWelcomeEn: "Welcome Message (English)",
    adminChatWelcomeZh: "Welcome Message (Chinese)",
    adminChatWelcomePlaceholder: "Enter chatbot welcome message...",
    adminChatQuickAskPlaceholder: "Enter quick ask label...",
    adminChatBtnToursEn: "Quick Ask: Recommend Tour (English)",
    adminChatBtnToursZh: "Quick Ask: Recommend Tour (Chinese)",
    adminChatBtnFoodEn: "Quick Ask: Food (English)",
    adminChatBtnFoodZh: "Quick Ask: Food (Chinese)",
    adminChatBtnPandaEn: "Quick Ask: Panda (English)",
    adminChatBtnPandaZh: "Quick Ask: Panda (Chinese)",
    adminChatResponsePlaceholder: "Enter chatbot response...",
    adminChatResToursEn: "Response: Tours (English)",
    adminChatResToursZh: "Response: Tours (Chinese)",
    adminChatResFoodEn: "Response: Food (English)",
    adminChatResFoodZh: "Response: Food (Chinese)",
    adminChatResPandaEn: "Response: Panda (English)",
    adminChatResPandaZh: "Response: Panda (Chinese)",
    adminChatDefaultResponseEn: "Fallback Response (English)",
    adminChatDefaultResponseZh: "Fallback Response (Chinese)",
    adminTravellerName: "Traveller Name",
    adminCountry: "Country",
    adminReviewTextEn: "Review Text (English)",
    adminReviewTextZh: "Review Text (Chinese)",
    adminQuestionEn: "Question (English)",
    adminQuestionZh: "Question (Chinese)",
    adminAnswerEn: "Answer (English)",
    adminAnswerZh: "Answer (Chinese)",
    adminLabelEnglish: "English",
    adminLabelChinese: "Chinese",
    adminAnswerLabel: "A",
    adminCancel: "Cancel",
    adminSaveReview: "Save Review",
    adminSaveFaq: "Save FAQ",
    adminEditReview: "Edit Review",
    adminEditFaq: "Edit FAQ",
    adminDelete: "Delete",
    adminEdit: "Edit",
    adminSaveTour: "Save Tour",
    adminAddNewTourFormTitle: "Add New Tour",
    adminEditTour: "Edit Tour",
    adminTitleEn: "Title (English)",
    adminTitleZh: "Title (Chinese)",
    adminDescriptionEn: "Description (English)",
    adminDescriptionZh: "Description (Chinese)",
    adminPrice: "Price (¥)",
    adminDuration: "Duration (hours)",
    adminImageUrl: "Image URL or Base64",
    adminImageUrlPlaceholder: "Paste URL from Gallery...",
    adminTags: "Tags (comma-separated)",
    adminStatusLabel: "Status",
    adminActiveVisible: "Active (Visible)",
    adminHidden: "Hidden",
    adminPopularLabel: "⭐ Mark as Popular",
    adminTitlePlaceholderEn: "The Ultimate Panda Experience",
    adminTitlePlaceholderZh: "大熊猫终极体验",
    adminDescriptionPlaceholderEn: "Describe the tour experience...",
    adminDescriptionPlaceholderZh: "描述旅行体验...",
    adminSampleName: "Sarah L.",
    adminSampleCountry: "USA",
    adminTagsPlaceholder: "Pandas, Nature",
    adminDurationPlaceholder: "3",
    adminPricePlaceholder: "450",
    adminGalleryCopyUrlTitle: "Copy URL",
    adminGalleryDeleteTitle: "Delete",
    adminImageCopiedAlert: "Image URL copied! You can paste it into the Tour Image field.",
    adminDeleteImageConfirm: "Delete this image? Tours using this image will be broken until updated.",
    adminDeleteReviewConfirmTemplate: "Delete review from \"{name}\"?",
    adminDeleteFaqConfirm: "Delete this FAQ?",
    adminDeleteTourConfirmTemplate: "Are you sure you want to delete \"{name}\"? This action cannot be undone.",
    adminStatusPending: "Pending",
    adminStatusContacted: "Contacted",
    adminStatusResolved: "Resolved",
    adminStatusEmailBtn: "Email",
    adminStatusContactBtn: "Contact",
    adminStatusResolveBtn: "Resolve",
    adminStatusPendingRequests: "Pending",
    adminTourBadgePopular: "⭐ Popular",
    adminTourBadgeHidden: "Hidden",
    adminTourBadgeActive: "Active",
    adminTourStatusCol: "Status",
    adminRequestEmailSubject: "Re: Panda Professor Tour Request",
    adminSaveSettings: "Settings saved!",
  },
  zh: {
    indexPageTitle: "熊猫教授 — 成都导游体验",
    indexMetaDescription: "由当地专家指导的真实、私密且知识渊博的成都游览体验。",
    menuLabel: "菜单",
    primaryNavigationAriaLabel: "主导航",
    homeLinkAriaLabel: "熊猫教授主页",
    openSidebarAriaLabel: "打开导航侧边栏",
    closeSidebarAriaLabel: "关闭导航侧边栏",
    langToggleAriaLabel: "切换语言",
    heroTitleP1: "与本地学者",
    heroTitleP2: "一起探索成都",
    heroSubtitle: "体验真正的四川精髓。从亲密接触大熊猫到寻找隐藏的美食瑰宝，通过热情专家的视角探索我的家乡。",
    bookNow: "规划您的旅程",
    viewTours: "探索体验",
    expertGuides: "专家向导",
    localScholars: "本地学者",
    authenticExp: "原汁原味",
    hiddenGems: "隐藏的瑰宝",
    maxComfort: "极致舒适",
    privatePremium: "私人定制",
    ourTours: "精选体验",
    filterAll: "全部",
    filterControlsLabel: "行程筛选器",
    filterCulture: "文化",
    filterFood: "美食",
    filterNature: "自然",
    filterPandas: "大熊猫",
    filterHistory: "历史",
    addToDay: "加入行程",
    removeFromDay: "从行程移除",
    tourFavorite: "加入收藏",
    tourUnfavorite: "移除收藏",
    planItemTime: "开始时间",
    planItemDuration: "时长（小时）",
    planItemPeople: "人数",
    planItemHours: "小时",
    planItemNotesPlaceholder: "可选备注（接送、酒店、餐食或其他要求）",
    reviewsTitle: "游客故事",
    sharePlan: "分享行程",
    clearPlan: "清空行程",
    dayBuilderTitle: "您的专属行程",
    dayBuilderNote: "拖动或点击卡片即可加入您的行程。",
    dayBuilderEmpty: "您的行程目前为空。请从上方列表中添加游览项目以定制完美的熊猫教授体验。",
    totalPrice: "预估总价",
    totalDuration: "总时长",
    bookPlan: "预订请求",
    faqTitle: "常见问题",
    bookingTitle: "预订请求",
    nameLabel: "姓名",
    emailLabel: "电子邮箱",
    dateLabel: "首选日期",
    guestsLabel: "人数",
    notesLabel: "特殊要求或备注",
    bookingNamePlaceholder: "李雷",
    bookingEmailPlaceholder: "example@email.com",
    bookingNotesPlaceholder: "过敏、航班时间等其他要求。",
    bookingInfoNote: "说明：我们将使用您的本地电子邮件客户端安全地生成请求。当前阶段不会收取任何费用。",
    bookingSuccessClose: "知道了！",
    submitBooking: "发送请求",
    close: "关闭",
    tourInclusions: "包含项目",
    tourExclusions: "不含项目",
    tourItinerary: "行程亮点",
    language: "语言",
    theme: "主题",
    searchPlaceholder: "搜索游览项目...",
    copied: "链接已复制！",
    linkCopiedMsg: "您的专属行程链接已复制到剪贴板。",
    bookingSuccessTitle: "请求已准备就绪",
    bookingSuccessMsg: "您的预订请求已生成。您的电子邮件客户端现在将打开，以便将请求直接发送给我们的团队。",
    chatWelcome: "你好！我是熊猫教授。🐼 今天我能帮你计划成都探险吗？",
    chatTitle: "熊猫教授",
    chatOnlineStatus: "在线",
    chatInputPlaceholder: "输入你的消息...",
    chatBtnTours: "推荐旅行",
    chatBtnFood: "成都美食怎么样？",
    chatBtnPanda: "告诉我一个熊猫事实！",
    skipToContent: "跳转到主要内容",
    themeSelectLabel: "主题",
    themeEmerald: "翡翠",
    themeForest: "森林",
    themeBamboo: "竹林",
    searchLabel: "搜索行程",
    chatDefaultResponse: "我现在只是一只演示熊猫 🐾 但当您预订时，一位真正的当地专家会回答您的问题！还有什么吗？",
    tourPopular: "热门",
    tourPriceTime: "价格与时间",
    tourView: "查看",
    tourDuration: "时长",
    tourHours: "小时",
    tourBasePrice: "基础价格",
    planTbd: "待定",
    chatResTours: "对于初次来客，强烈推荐“大熊猫保护晨间探秘之旅”；对美食爱好者，“成都夜生活与川味餐桌”是绝佳选择。🎋",
    chatResFood: "成都是被联合国教科文组织评选为世界美食之都！期待大胆的风味，令人麻木的四川花椒和冒泡的火锅。我们可以为您定制辣度。🌶️",
    chatResPanda: "你知道一只大熊猫每天要花 10-16 个小时吃东西吗？他们每天可以吃掉高达 38 公斤的竹子！我很尊重那种对零食的奉献精神。🎋🐾",
    footerAbout: "由当地专家指导的真实，私人且知识渊博的成都概览。",
    footerBrandTagline: "成都行程",
    footerAriaLabel: "熊猫教授页脚信息",
    footerEmailLabel: "邮箱",
    footerPhoneLabel: "电话",
    footerEmailA11y: "邮件咨询熊猫教授",
    footerPhoneA11y: "电话咨询熊猫教授",
    footerSocialLabel: "关注熊猫教授",
    socialLinksLabel: "社交媒体频道",
    footerQuickLinks: "快速链接",
    footerContact: "联系方式",
    footerPlanning: "行程规划",
    footerFollowUs: "关注我们",
    footerCta: "下单前先咨询，我们会按您的偏好调整日程。",
    footerCopyright: "© {year} 熊猫教授成都行程. 保留所有权利。",
    footerBrandAriaLabel: "访问熊猫教授",
    footerQuickLinksAriaLabel: "页脚快速链接",
    footerPlanningAriaLabel: "页脚规划链接",
    footerSocialNavAriaLabel: "页脚社交媒体链接",
    footerSocialInstagram: "Instagram",
    footerSocialFacebook: "Facebook",
    footerSocialTwitter: "Twitter",
    footerSocialWeibo: "微博",
    footerSocialXiaohongshu: "小红书",
    footerSocialWeChat: "微信",
    footerSocialWeChatTip: "在微信搜索或扫码 {wechatId}",
    closeModalAriaLabel: "关闭对话框",
    closeBookingFormAriaLabel: "关闭预订表单",
    closeSuccessMessageAriaLabel: "关闭成功提示",
    chatTriggerAriaLabel: "打开熊猫聊天助手",
    chatPanelAriaLabel: "熊猫聊天助手",
    chatCloseAriaLabel: "关闭熊猫聊天",
    sendMessageAriaLabel: "发送消息",
    adminPageTitle: "熊猫教授 — 管理后台",
    adminMetaDescription: "熊猫教授成都旅行管理后台。",
    adminAdminLogin: "管理员登录",
    adminPinHint: "请输入管理员 PIN 码以访问控制面板。",
    adminInvalidPin: "PIN 码无效，请重试。",
    adminPinLabel: "管理员 PIN",
    adminSignInAriaLabel: "登录管理员后台",
    adminSignIn: "登录",
    adminLanguageToggleAriaLabel: "切换后台语言",
    adminHint: "提示",
    adminDefaultPin: "默认 PIN：",
    adminDefaultPinValue: "admin",
    adminAdminText: "管理员",
    adminViewSite: "查看网站",
    adminViewSiteAriaLabel: "打开公开站点",
    adminLogout: "登出",
    adminLogoutAriaLabel: "退出登录",
    adminHomeAriaLabel: "管理员首页",
    adminLanguage: "语言",
    adminActiveTours: "在售行程",
    adminPendingRequests: "待处理请求",
    adminResolved: "已处理",
    adminBookingRequests: "预订请求",
    adminTourOfferings: "路线管理",
    adminGallery: "图片库",
    adminSettings: "设置",
    adminReviews: "游客评价",
    adminFaqs: "常见问题",
    adminDate: "日期",
    adminName: "姓名",
    adminEmail: "电子邮箱",
    adminGuests: "人数",
    adminTours: "行程",
    adminStatus: "状态",
    adminActions: "操作",
    adminNoBookingRequests: "目前没有预订请求。",
    adminNoRequestsSub: "游客在公开页提交的请求会显示在这里。",
    adminAddReview: "添加评论",
    adminTravellerStories: "游客故事",
    adminAddFaq: "添加常见问题",
    adminFrequentlyAskedQuestions: "常见问题",
    adminAddNewTour: "新增路线",
    adminUploadImage: "上传图片",
    adminChangeAdminPin: "修改管理员 PIN",
    adminNewPin: "新 PIN",
    adminNewPinPlaceholder: "输入新的 PIN",
    adminUpdatePin: "更新 PIN",
    adminPinUpdated: "PIN 更新成功！",
    adminSiteContact: "网站信息与联系方式",
    adminSiteName: "网站名称",
    adminContactEmail: "联系邮箱",
    adminContactPhone: "联系电话",
    adminBrandLogo: "品牌 Logo 链接",
    adminBrandLogoPlaceholder: "logo.png 或 https://cdn.example.com/logo.svg",
    adminBrandLogoHint: "用于页头、页脚、聊天和后台品牌展示。",
    adminSocialLinks: "社交媒体链接",
    adminInstagram: "Instagram",
    adminFacebook: "Facebook",
    adminTwitter: "Twitter / X",
    adminWeChat: "微信（用户名 / ID）",
    adminWeibo: "微博链接",
    adminXiaohongshu: "小红书链接",
    adminInstagramPlaceholder: "https://instagram.com/...",
    adminFacebookPlaceholder: "https://facebook.com/...",
    adminTwitterPlaceholder: "https://twitter.com/...",
    adminWeChatPlaceholder: "微信号",
    adminWeiboPlaceholder: "https://weibo.com/...",
    adminXiaohongshuPlaceholder: "https://xiaohongshu.com/...",
    adminSettingsSaved: "设置已保存！",
    adminSaveChanges: "保存更改",
    adminChatCopyHeading: "机器人文案设置",
    adminChatWelcomeEn: "欢迎语（英文）",
    adminChatWelcomeZh: "欢迎语（中文）",
    adminChatWelcomePlaceholder: "输入欢迎语...",
    adminChatQuickAskPlaceholder: "输入快捷问题文案...",
    adminChatBtnToursEn: "快捷问题：推荐行程（英文）",
    adminChatBtnToursZh: "快捷问题：推荐行程（中文）",
    adminChatBtnFoodEn: "快捷问题：美食（英文）",
    adminChatBtnFoodZh: "快捷问题：美食（中文）",
    adminChatBtnPandaEn: "快捷问题：熊猫（英文）",
    adminChatBtnPandaZh: "快捷问题：熊猫（中文）",
    adminChatResponsePlaceholder: "输入机器人回复...",
    adminChatResToursEn: "回复：行程（英文）",
    adminChatResToursZh: "回复：行程（中文）",
    adminChatResFoodEn: "回复：美食（英文）",
    adminChatResFoodZh: "回复：美食（中文）",
    adminChatResPandaEn: "回复：熊猫（英文）",
    adminChatResPandaZh: "回复：熊猫（中文）",
    adminChatDefaultResponseEn: "兜底回复（英文）",
    adminChatDefaultResponseZh: "兜底回复（中文）",
    adminTravellerName: "游客姓名",
    adminCountry: "国家",
    adminReviewTextEn: "英文评论",
    adminReviewTextZh: "中文评论",
    adminQuestionEn: "英文问题",
    adminQuestionZh: "中文问题",
    adminAnswerEn: "英文回答",
    adminAnswerZh: "中文回答",
    adminLabelEnglish: "英文",
    adminLabelChinese: "中文",
    adminAnswerLabel: "回答",
    adminCancel: "取消",
    adminSaveReview: "保存评论",
    adminSaveFaq: "保存问题",
    adminEditReview: "编辑评论",
    adminEditFaq: "编辑问题",
    adminDelete: "删除",
    adminEdit: "编辑",
    adminSaveTour: "保存路线",
    adminAddNewTourFormTitle: "新增路线",
    adminEditTour: "编辑路线",
    adminTitleEn: "英文标题",
    adminTitleZh: "中文标题",
    adminDescriptionEn: "英文描述",
    adminDescriptionZh: "中文描述",
    adminPrice: "价格（¥）",
    adminDuration: "时长（小时）",
    adminImageUrl: "图片链接或 Base64",
    adminImageUrlPlaceholder: "从图库粘贴图片链接...",
    adminTags: "标签（逗号分隔）",
    adminStatusLabel: "状态",
    adminActiveVisible: "展示中",
    adminHidden: "隐藏",
    adminPopularLabel: "⭐ 标记为热门",
    adminTitlePlaceholderEn: "大熊猫终极体验",
    adminTitlePlaceholderZh: "大熊猫终极体验",
    adminDescriptionPlaceholderEn: "填写路线体验描述...",
    adminDescriptionPlaceholderZh: "填写路线体验描述...",
    adminSampleName: "李雷",
    adminSampleCountry: "中国",
    adminTagsPlaceholder: "Pandas, Nature",
    adminDurationPlaceholder: "3",
    adminPricePlaceholder: "450",
    adminGalleryCopyUrlTitle: "复制链接",
    adminGalleryDeleteTitle: "删除",
    adminImageCopiedAlert: "图片链接已复制，可粘贴到“图片链接或 Base64”字段。",
    adminDeleteImageConfirm: "确定要删除该图片？正在使用的行程图片可能会暂时失效。",
    adminDeleteReviewConfirmTemplate: "确定要删除“{name}”的游客评价吗？",
    adminDeleteFaqConfirm: "确定要删除这条常见问题吗？",
    adminDeleteTourConfirmTemplate: "确定要删除“{name}”吗？该操作不可撤销。",
    adminStatusPending: "待处理",
    adminStatusContacted: "已联系",
    adminStatusResolved: "已完成",
    adminStatusEmailBtn: "邮件",
    adminStatusContactBtn: "联系",
    adminStatusResolveBtn: "完成",
    adminStatusPendingRequests: "待处理",
    adminTourBadgePopular: "⭐ 热门",
    adminTourBadgeHidden: "隐藏",
    adminTourBadgeActive: "展示中",
    adminTourStatusCol: "状态",
    adminRequestEmailSubject: "回复：熊猫教授旅行请求",
    adminSaveSettings: "设置已保存！",
  }
};

const tours = [
  {
    id: "t1",
    titleEn: "Dawn Panda Conservation Expedition",
    titleZh: "大熊猫保护晨间探秘之旅",
    descEn: "Join a curator-led dawn walk at a conservation-focused breeding base, and spend a full morning learning husbandry routines, enrichment activities, and habitat care.",
    descZh: "跟随资深导览员参与清晨工作体验，深入了解熊猫饲养流程、行为观察与环境保护工作。",
    price: 1680,
    duration: 5.5,
    image: "images/panda1.jpg",
    tags: ["Pandas", "Nature"],
    popular: true,
    inclusionsEn: ["Private pickup/drop-off in AC minivan", "Conservation briefing", "Base access + guided circulation", "Lunch", "Expert interpretation"],
    inclusionsZh: ["空调小巴接送", "保护解读简报", "基地参观与解说", "午餐", "专家讲解"],
    exclusionsEn: ["Personal souvenirs", "Tips", "Outside meals"],
    exclusionsZh: ["个人消费", "小费", "景区外餐食"]
  },
  {
    id: "t2",
    titleEn: "Night Market & Sichuan Food Journey",
    titleZh: "成都夜生活与川味餐桌",
    descEn: "A guided exploration of late-evening food alleys, classic hotpot culture, and craft beverages curated to suit different spice tolerances.",
    descZh: "夜间在导游带领下穿行美食街，体验地道火锅与小吃文化，并根据辣度偏好做个性化推荐。",
    price: 520,
    duration: 3.5,
    image: "images/panda2.jpg",
    tags: ["Food", "Culture"],
    popular: true,
    inclusionsEn: ["Food tasting route", "Spice-level guidance", "Local drink pairing", "Food cart tasting notes"],
    inclusionsZh: ["美食路线规划", "辣度建议与讲解", "饮品搭配", "品鉴说明卡"],
    exclusionsEn: ["Transport to first meeting point", "Any personal drinks"],
    exclusionsZh: ["到达集合点交通", "个人酒水与加购项目"]
  },
  {
    id: "t3",
    titleEn: "Sanxingdui Discovery with Senior Curator",
    titleZh: "三星堆考古解码之旅",
    descEn: "A private interpretation of bronze masks, jade artifacts, and ritual bronzeworks with an emphasis on what makes Sanxingdui one of China's greatest unsolved cultural discoveries.",
    descZh: "由策展人视角带您解读青铜面具、玉器与青铜礼器，理解三星堆为何是中国最具震撼力的古文明之谜。",
    price: 680,
    duration: 6,
    image: "images/panda3.jpg",
    tags: ["History", "Culture"],
    popular: false,
    inclusionsEn: ["Private transfer", "Museum admission", "Curator-led interpretation", "Printed artifact timeline"],
    inclusionsZh: ["私人接送", "博物馆门票", "专家讲解", "文物时间线手册"],
    exclusionsEn: ["Lunch", "Optional private photography kit"],
    exclusionsZh: ["午餐", "可选拍照设备租赁"]
  },
  {
    id: "t4",
    titleEn: "Leshan Buddha & Tea Terraces Immersion",
    titleZh: "乐山大佛与茶园日环线",
    descEn: "Visit one of the largest Buddha statues in the world, then retreat to a nearby historic tea valley for a guided tasting and tea ceremony style session.",
    descZh: "探访世界级石刻奇观乐山大佛，之后前往古茶园体验制茶与茶文化导览。",
    price: 920,
    duration: 9,
    image: "images/panda4.jpg",
    tags: ["History", "Nature"],
    popular: false,
    inclusionsEn: ["Boat route transfer", "Leshan admission", "Tea valley visit", "Guided tea tasting"],
    inclusionsZh: ["游船往返路线", "景区门票", "茶园参观", "专业茶品体验"],
    exclusionsEn: ["Lunch", "Hotel transfer outside itinerary"],
    exclusionsZh: ["午餐", "行程外酒店接送"]
  },
  {
    id: "t5",
    titleEn: "Sichuan Opera: Masks, Musicians and Backstage",
    titleZh: "川剧变脸与幕后观演",
    descEn: "Witness bian lian artistry on stage, then join an exclusive backstage segment for a short backstage conversation and performance walkthrough.",
    descZh: "观看正宗川剧变脸，并进入后台进行简短交流，了解变脸、锣鼓、面部妆艺技巧。",
    price: 420,
    duration: 3,
    image: "images/panda5.jpg",
    tags: ["Culture", "History"],
    inclusionsEn: ["Performance tickets", "Backstage access", "Meet-and-greet with stage manager", "Tea and snacks"],
    inclusionsZh: ["演出门票", "后台通行", "舞台经理见面交流", "茶点"],
    exclusionsEn: ["Transport"],
    exclusionsZh: ["交通"]
  },
  {
    id: "t6",
    titleEn: "Classical Sichuan Kitchen Masterclass",
    titleZh: "川味私房烹饪工作坊",
    descEn: "Shop at a traditional market with a culinary guide, then cook Mapo Tofu, Kung Pao Chicken, and one noodle specialist dish in a historic courtyard.",
    descZh: "跟随美食向导逛传统市场，随后在历史院落中制作经典川菜。",
    price: 560,
    duration: 4,
    image: "images/panda6.jpg",
    tags: ["Food", "Culture"],
    popular: true,
    inclusionsEn: ["Market route", "Chef-led class", "All ingredients", "Dining of dishes you cook", "Takeaway spices"],
    inclusionsZh: ["菜市场导览", "厨师课堂", "全部食材", "成品午餐/晚餐", "香料包带走"],
    exclusionsEn: [],
    exclusionsZh: []
  },
  {
    id: "t7",
    titleEn: "Dufu Legacy Literary Walk",
    titleZh: "杜甫文学与园林讲坛",
    descEn: "A scholar-guided walk through Dufu's residences and gardens, connecting poetry, tea culture, and the urban ecology of historic Chengdu neighborhoods.",
    descZh: "由学者带队走访杜甫草堂与历史街区，理解诗词、茶道与成都古城生态之间的关系。",
    price: 390,
    duration: 3,
    image: "images/panda7.jpg",
    tags: ["History", "Culture"],
    inclusionsEn: ["Entry tickets", "Calligraphy station", "Tea set", "Small-group narration"],
    inclusionsZh: ["园区门票", "书法体验", "茶具体验", "小班讲解"],
    exclusionsEn: ["Transport"],
    exclusionsZh: ["交通"]
  },
  {
    id: "t8",
    titleEn: "Qingcheng Mountain Taoist Breathing Trail",
    titleZh: "青城山道教气息之旅",
    descEn: "A gentle mountain and temple route with breathing practice, temple etiquette guidance, and optional bamboo tea stop at a mountain rest pavilion.",
    descZh: "结合轻徒步与道教文化体验，学习呼吸与礼仪常识，并在茶亭短暂停留。",
    price: 860,
    duration: 7,
    image: "images/panda8.jpg",
    tags: ["Nature", "History"],
    inclusionsEn: ["Round-trip transport", "Entry tickets", "Cable car option", "Guided breathing session"],
    inclusionsZh: ["往返交通", "门票", "可选缆车", "太极/呼吸练习"],
    exclusionsEn: ["Lunch"],
    exclusionsZh: ["午餐", "行程外酒店接送"]
  },
  {
    id: "t9",
    titleEn: "Early Panda Research Base Private Access",
    titleZh: "熊猫科研基地朝会体验",
    descEn: "Enter before peak visitor hours, observe keeper routines, and walk through juvenile panda nurseries with a bilingual guide trained in animal behavior communication.",
    descZh: "避开高峰人流进入基地，近距离观察护养流程，并在双语向导带领下了解幼崽保育区。",
    price: 620,
    duration: 4,
    image: "images/panda9.jpg",
    tags: ["Pandas", "Nature"],
    inclusionsEn: ["Priority access", "Behavior interpretation", "Expert guide", "Printed schedule"],
    inclusionsZh: ["优先入园", "行为观察讲解", "专业向导", "行程手册"],
    exclusionsEn: ["Breakfast", "Photo licensing requests"],
    exclusionsZh: ["早餐", "商业拍摄授权"]
  },
  {
    id: "t10",
    titleEn: "Wolong Tea Village & Bamboo Grove Ride",
    titleZh: "卧龙茶乡与竹林慢旅",
    descEn: "Spend a full morning among tea growers and bamboo groves, learning processing steps and taking short rides to scenic valleys with dedicated photography opportunities.",
    descZh: "深度体验茶园与竹林环境，了解采摘和加工流程，并安排短线观景行程。",
    price: 500,
    duration: 5,
    image: "images/panda10.jpg",
    tags: ["Nature", "Culture"],
    inclusionsEn: ["Bamboo route transfer", "Tea tasting", "Tea processing demo", "Photo assistant"],
    inclusionsZh: ["茶乡接送", "茶品体验", "制茶演示", "摄影协助"],
    exclusionsEn: ["Lunch", "Extra tea blends"],
    exclusionsZh: ["午餐", "额外茶叶礼盒"]
  }
];

const reviews = [
  {
    name: "Sarah L.",
    country: "USA",
    avatar: "images/panda6.jpg",
    rating: 5,
    textEn: "The Panda Volunteer day was life-changing. Our guide from Panda Professor was incredibly knowledgeable and handled all the logistics perfectly.",
    textZh: "大熊猫义工体验改变了我一生。熊猫教授的向导知识非常渊博，并且完美地处理了所有后勤工作。"
  },
  {
    name: "Marcus T.",
    country: "Germany",
    avatar: "images/panda7.jpg",
    rating: 5,
    textEn: "We did the midnight food tour. We expected spicy, but we didn't expect how complex and delicious the flavors would be. Highly recommended for foodies.",
    textZh: "我们参加了午夜美食之旅。我们预料到会很辣，但没想到味道会如此复杂和美味。强烈推荐给美食家。"
  },
  {
    name: "Emma & James",
    country: "UK",
    avatar: "images/panda8.jpg",
    rating: 5,
    textEn: "Sanxingdui was unbelievable. Having a proper historian explain the mysteries made the artifacts come alive. Best day of our China trip.",
    textZh: "三星堆令人难以置信。有一位真正的历史学家来解释这些未解之谜，让文物变得栩栩如生。这是我们中国之行最棒的一天。"
  },
  {
    name: "David W.",
    country: "Australia",
    avatar: "images/panda9.jpg",
    rating: 4,
    textEn: "The cooking masterclass was the highlight of our trip. Shopping at the local market first gave us a real feel for daily life in Chengdu.",
    textZh: "烹饪大师课是我们旅程的亮点。首先在当地市场购物，让我们真正体会到了成都的日常生活。"
  },
  {
    name: "Lena H.",
    country: "France",
    avatar: "images/panda10.jpg",
    rating: 5,
    textEn: "Incredible attention to detail from the Panda Professor team. The Leshan Giant Buddha boat tour was timed perfectly to avoid the massive crowds.",
    textZh: "熊猫教授团队对细节的关注令人难以置信。乐山大佛游船的时间安排得非常完美，避开了拥挤的人群。"
  },
  {
    name: "Alyssa P.",
    country: "Canada",
    avatar: "images/panda1.jpg",
    rating: 5,
    textEn: "The tea valley route was beautifully paced. Even though it was a long day, we still had enough time for a relaxing tea ceremony and meaningful photos.",
    textZh: "茶园路线安排得很舒适，尽管行程很长，我们仍有足够时间享受放松的茶道体验和拍照时光。"
  },
  {
    name: "Yuki K.",
    country: "Japan",
    avatar: "images/panda2.jpg",
    rating: 4,
    textEn: "Our family loved the panda conservation visit. The guide adapted explanations for our children and made every stop educational without being overwhelming.",
    textZh: "我们全家都很喜欢熊猫保护参观。导游为孩子调整讲解方式，让每个站点都很有趣又有教育意义。"
  },
  {
    name: "Mateo & Chiara",
    country: "Spain",
    avatar: "images/panda3.jpg",
    rating: 5,
    textEn: "Chef-led cooking at the courtyard was the standout experience. We went home with a skill set, fresh ingredients, and confidence to cook Sichuan dishes ourselves.",
    textZh: "院落里的厨师课堂是最亮眼的体验。我们回到家里带着技能、食材技巧，也更有信心自己做川菜。"
  }
];

const faqs = [
  {
    qEn: "How do I book a private tour, and can I customize it?",
    qZh: "我如何预订私人行程？可否定制？",
    aEn: "Every visit is built from your request. Use the Day Builder or contact us directly for language, group size, pace, mobility needs, and must-see priorities. We tailor routes and cut or combine modules to match your interests.",
    aZh: "每个行程都可按需求定制。请在行程构建器中设置偏好，或直接联系我们，说明语言、人数、节奏、行动便利性和重点景点，我们可根据您需求调整路线。"
  },
  {
    qEn: "Do tours include transport between sites?",
    qZh: "行程是否包含景点之间的交通？",
    aEn: "Most premium itineraries include climate-controlled private minivan transfer. For compact city experiences, we often combine walks with metro guidance to reduce cost and waiting time. Transfer details are confirmed in the final itinerary confirmation.",
    aZh: "多数高端行程包含景点间空调小巴接送。若为市中心短线游，我们会结合步行与地铁指引，以节省成本和等待时间。最终行程确认单会明确接送安排。"
  },
  {
    qEn: "Is the group size fixed or private?",
    qZh: "行程是固定团体还是可私人定制？",
    aEn: "Core experiences are available as private/private-plus packages with adjustable guest capacity. We can design intimate groups, family itineraries, or mixed-language tours. Group size is confirmed by the itinerary summary before payment.",
    aZh: "核心体验支持纯私人团或小团定制，可灵活设置人数上限、家庭出行或双语导览。最终报名确认会再次确认人数与服务安排。"
  },
  {
    qEn: "What payment methods do you accept, and when is payment required?",
    qZh: "贵司支持哪些支付方式？何时需要付款？",
    aEn: "We accept international cards and major local transfer methods listed upon request. A reservation summary is sent before travel, and deposits are requested only for finalized confirmed bookings. We never request sensitive card details through messaging apps.",
    aZh: "我们支持国际卡及常见本地转账方式（按需提供清单）。在出行前会发送确认方案，确认后需要支付定金。我们不会通过聊天工具索要敏感的银行卡信息。"
  },
  {
    qEn: "How flexible is the cancellation policy?",
    qZh: "取消政策有多大灵活性？",
    aEn: "Cancellations made 48+ hours before confirmed start time are eligible for a full refund (service fee excluded). For weather or safety-driven postponements, we prioritize rebooking with equal or premium options and keep communication transparent.",
    aZh: "确认行程开始前 48 小时及以上取消可申请全额退费（不含服务费）。若因天气或安全原因改期，我们优先安排同等或更高等级的可用档期，并保持透明沟通。"
  },
  {
    qEn: "Do you support accessibility needs and dietary/allergy requests?",
    qZh: "是否支持无障碍和过敏需求？",
    aEn: "Yes. We support stroller-friendly routes, extra rest windows, and reduced walking options where possible. Allergy and spice requirements are noted during booking, and we brief all providers before execution.",
    aZh: "我们支持婴儿车/轮椅友好路线、增加中途休息和可选减少步行行程。过敏和辣度需求会在预订阶段记录，并在行程执行前同步给服务团队。"
  }
];

const pandaFacts = [
  {
    textEn: "A giant panda spends 10-16 hours a day eating! They can consume up to 38kg of bamboo a day! 🎋🐾",
    textZh: "一只大熊猫每天要花 10-16 个小时吃东西！他们每天可以吃掉高达 38 公斤的竹子！🎋🐾"
  },
  {
    textEn: "Newborn pandas are about the size of a stick of butter—around 1/900th the size of their mother! 🧈🐼",
    textZh: "刚出生的熊猫只有大约一块黄油那么大——大约是它们母亲体型的 1/900！🧈🐼"
  },
  {
    textEn: "Wild giant pandas live mainly in the bamboo forests high in the mountains of western China, right here in Sichuan! ⛰️🇨🇳",
    textZh: "野生大熊猫主要生活在中国西部高山上的竹林中，就在这四川！⛰️🇨🇳"
  },
  {
    textEn: "Despite being classified as carnivores, their diet is 99% bamboo. They occasionally eat small animals or fish. 🐟🥬",
    textZh: "尽管被归类为食肉动物，但它们的饮食中 99% 是竹子。它们偶尔也会吃些小动物或鱼。🐟🥬"
  },
  {
    textEn: "Pandas have an extended wrist bone that acts like a thumb, helping them hold bamboo stalks perfectly. 👍🌱",
    textZh: "大熊猫有一块延伸的腕骨，其作用就像拇指一样，可以帮助它们完美地握住竹茎。👍🌱"
  },
  {
    textEn: "Unlike other bears, giant pandas do not hibernate! Their bamboo diet doesn't allow them to build up enough fat reserves for winter. ❄️🏃‍♂️",
    textZh: "与其他熊类不同，大熊猫不冬眠！它们以竹子为食，这使得它们无法在冬天积累足够的脂肪储备。❄️🏃‍♂️"
  },
  {
    textEn: "Adult giant pandas generally live solitary lives, only coming together briefly to mate. 🚶‍♂️☁️",
    textZh: "成年大熊猫通常过着独居生活，只有在交配时才会短暂相聚。🚶‍♂️☁️"
  }
];

window.appData = {
  translations,
  tours,
  reviews,
  faqs,
  pandaFacts
};
